---
title: "04 Donut Chart, Line Graph"
author: "Tara Jaigopal"
date: "2/15/2021"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r, message=FALSE, warning=FALSE}
# packages
library(readr)
library(tidyverse)
library(plotly)
```

```{r, message=FALSE, warning=FALSE}
# reading in primary dataset 
avocados <- read_csv("datasets [final]/avo_combined.csv")
avocados$Type[avocados$Type == "conventional"] <- "Conventional"
avocados$Type[avocados$Type == "organic"] <- "Organic"

# defining regions
regions <- c("West","South Central","California", "Northeast","Southeast","Great Lakes","Midsouth","Plains")
```

# Donut Charts 

## Filtering & Summarizing

```{r, message=FALSE}
# separating into organic vs. conventional avocados
avocados_type <- avocados %>% filter(Region == 'Total U.S.' | Region %in% regions) %>% 
  group_by(Region, Type) %>% 
  summarise(AveragePrice=mean(AveragePrice), TotalVolume = sum(`Total Volume`))
avocados_type    
```

## Creating Visualization

```{r}
# creating series of donut charts
donuts <- plot_ly()
donuts <- donuts %>% add_pie(data = avocados_type[15:16,], labels = ~Type, 
                             values = ~TotalVolume, name = "Total U.S",
                             marker = list(colors = c("#4B9750", "#8FD17F")),
                             domain = list(row = 0, column = 0), hole = 0.6, 
                             textinfo="none", title = "Total U.S.")
donuts <- donuts %>% add_pie(data = avocados_type[11:12,], labels = ~Type, 
                             values = ~TotalVolume, name = "South Central",
                             marker = list(colors = c("#4B9750", "#8FD17F")),
                             domain = list(row = 0, column = 1), hole = 0.6,
                             textinfo="none", title = "South Central")
donuts <- donuts %>% add_pie(data = avocados_type[13:14,], labels = ~Type, 
                             values = ~TotalVolume, name = "Southeast",
                             marker = list(colors = c("#4B9750", "#8FD17F")),
                             domain = list(row = 0, column = 2), hole = 0.6,
                             textinfo="none", title = "Southeast")
donuts <- donuts %>% add_pie(data = avocados_type[9:10,], labels = ~Type, 
                             values = ~TotalVolume, name = "Plains",
                             marker = list(colors = c("#4B9750", "#8FD17F")),
                             domain = list(row = 1, column = 0), hole = 0.6,
                             textinfo="none", title = "Plains")
donuts <- donuts %>% add_pie(data = avocados_type[1:2,], labels = ~Type, 
                             values = ~TotalVolume, name = "California",
                             marker = list(colors = c("#4B9750", "#8FD17F")),
                             domain = list(row = 1, column = 1), hole = 0.6,
                             textinfo="none", title = "California")
donuts <- donuts %>% add_pie(data = avocados_type[17:18,], labels = ~Type, 
                             values = ~TotalVolume, name = "West",
                             marker = list(colors = c("#4B9750", "#8FD17F")),
                             domain = list(row = 1, column = 2), hole = 0.6,
                             textinfo="none", title = "West")
donuts <- donuts %>% add_pie(data = avocados_type[7:8,], labels = ~Type, 
                             values = ~TotalVolume, name = "Northeast",
                             marker = list(colors = c("#4B9750", "#8FD17F")),
                             domain = list(row = 2, column = 0), hole = 0.6,
                             textinfo="none", title = "Northeast")
donuts <- donuts %>% add_pie(data = avocados_type[5:6,], labels = ~Type, 
                             values = ~TotalVolume, name = "Midsouth",
                             marker = list(colors = c("#4B9750", "#8FD17F")),
                             domain = list(row = 2, column = 1), hole = 0.6,
                             textinfo="none", title = "Midsouth")
donuts <- donuts %>% add_pie(data = avocados_type[3:4,], labels = ~Type, 
                             values = ~TotalVolume, name = "Great Lakes",
                             marker = list(colors = c("#4B9750", "#8FD17F")),
                             domain = list(row = 2, column = 2), hole = 0.6,
                             textinfo="none", title = "Great Lakes")
donuts <- donuts %>% layout(title = "Proportion of Conventional vs. Organic Avocados Purchased Between 2015 and 2020",
                      grid=list(rows=3, columns=3),
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

donuts
```

# Line Graph

## Filtering & Summarizing

```{r}
# separating into conventional & organix avocados
avocados_organic <- avocados %>% filter(Region == "Total U.S." & Type == "Organic") %>% select(Region, Date, Type, AveragePrice) %>% arrange(Date)
avocados_conventional <- avocados %>% filter(Region == "Total U.S." & Type == "Conventional") %>% select(Region, Date, Type, AveragePrice) %>% arrange(Date)
```

## Creating Visualization

```{r}
linegraph <- plot_ly(data = avocados_conventional, x = ~Date, y = ~AveragePrice,
                      type = "scatter", mode = "lines",
                      color = I("#4B9750"), name = "Conventional")
linegraph <- linegraph %>% 
  add_trace(data = avocados_organic, x = ~Date, y = ~AveragePrice, 
            mode = "lines", color = I("#8FD17F"), name = "Organic") 
linegraph <- linegraph %>% 
  layout(title = "Average Price of Conventional vs. Organic Avocados",
         yaxis = list(title="Average Price of Avocado in US $"))

linegraph
```

## Finding average difference in price between different types of avocados

```{r}
mean(avocados_organic$AveragePrice - avocados_conventional$AveragePrice)
```
