---
title: "06 Scatterplot"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r, message=FALSE, warning=FALSE}
# packages
library(readr)
library(tidyverse)
library(plotly)
```

```{r, message=FALSE, warning=FALSE}
# reading in datasets
avocados <- read_csv("datasets [final]/avo_combined.csv")
cities <- read_delim("datasets [final]/us-cities-demographics.csv", ";")

# summarizing city data
cities <- cities %>% group_by(City) %>% 
  summarize(MedianAge = median(`Median Age`), 
            TotalPop = mean(`Total Population`))

# defining regions
regions <- c("West","South Central","California", "Northeast","Southeast","Great Lakes","Midsouth","Plains")
```

# Scatterplot

## Filtering & Summarizing

```{r, warnings = FALSE, message=FALSE}
avocados <- avocados %>% mutate(Year = format(as.Date(avocados$Date, format="%Y-%m-%d"),"%Y"))
avocados2 <- avocados %>% filter(!(Region %in% regions) & Region != "Total U.S.") %>%
  group_by(Region) %>%
  summarise(TotalVolume = sum(`Total Volume`))
avocados3 <- merge(avocados2, cities, by.x = "Region", by.y = "City")
avocados3 <- avocados3 %>% mutate(PerCapitaVolume = TotalVolume/TotalPop)

# not all medians are available (e.g. median of "Baltimore-Washington")

```

## Creating Visualization

```{r, message=FALSE}
# let's do a scatterplot 
t <- list(size = 8, color = toRGB("grey50"))
scatterplot <- plot_ly(avocados3, x= ~MedianAge, y= ~PerCapitaVolume, text = ~Region, color = I("#195B19")) %>% layout(title = "Median Age of Residents vs. Per Capita Avocado Purchases", xaxis= list(title = "Median Age in Years"), yaxis = list(title="Units of Avocados Purchased Per Capita"))
scatterplot
```
